### ISSUE TITLE
I've found a bug when process the bitmap with only white and black pixels

### ISSUE THREAD

**Issue by neo5anderson** [aisk/pic2ascii#1]
have a look at newest pic2ascii.py at line 19
I think:

```
    output += chars[(pixs[x,y]/10) % len(chars)]
```

will be much better than:

```
    output += chars[pixs[x,y]/10]
```

Because when I convert my pics, I always got:

  IndexError: string index out of range

**Comment by neo5anderson** [comment]
Here is my test image:
![c](https://f.cloud.github.com/assets/1518241/35043/4998a050-5184-11e2-8506-8189a1bbd879.png)

**Comment by 123Daoxyz** [comment]
+1

**Comment by aisk** [comment]
Sorry late for the reply for seven years, seems I saw this issue and forgot to reply. Actually this problem seems can not reproduced on my machine with current pillow version (so many versions released after senven years...). Looks like they changed the behavior with some release. Please contact me if you got any issue now, I think I have more knowledges on fix bugs in these years.

And thanks for the patient for waiting seven years.

![捕获](https://user-images.githubusercontent.com/699636/59113949-b22ec080-8978-11e9-8d84-52e08723abc8.PNG)
